aliases: []
creation_timestamp: 1711649657066
current_stage: None
description: ''
last_updated_timestamp: 1711649657066
name: sentiment_analysis_prediction
run_id: a12a429352cf4891b4236fb14b708b35
run_link: ''
source: file:///C:/Users/NAVYA/Downloads/MY_PYTHON_PRACTICE/Innomatics_internship/jup_vir_env/Scripts/ML_flow_Sentiment_analysis/mlruns/972715570874921247/a12a429352cf4891b4236fb14b708b35/artifacts/best_estimator
status: READY
status_message: null
storage_location: file:///C:/Users/NAVYA/Downloads/MY_PYTHON_PRACTICE/Innomatics_internship/jup_vir_env/Scripts/ML_flow_Sentiment_analysis/mlruns/972715570874921247/a12a429352cf4891b4236fb14b708b35/artifacts/best_estimator
user_id: null
version: 5
