aliases: []
creation_timestamp: 1711649171232
current_stage: Production
description: ''
last_updated_timestamp: 1711687569176
name: sentiment_analysis_prediction
run_id: 50f66a3fcdc44cc79da92a4f89789869
run_link: ''
source: file:///C:/Users/NAVYA/Downloads/MY_PYTHON_PRACTICE/Innomatics_internship/jup_vir_env/Scripts/ML_flow_Sentiment_analysis/mlruns/972715570874921247/50f66a3fcdc44cc79da92a4f89789869/artifacts/best_estimator
status: READY
status_message: null
storage_location: file:///C:/Users/NAVYA/Downloads/MY_PYTHON_PRACTICE/Innomatics_internship/jup_vir_env/Scripts/ML_flow_Sentiment_analysis/mlruns/972715570874921247/50f66a3fcdc44cc79da92a4f89789869/artifacts/best_estimator
user_id: null
version: 1
