aliases: []
creation_timestamp: 1711649525081
current_stage: Archived
description: ''
last_updated_timestamp: 1711687569176
name: sentiment_analysis_prediction
run_id: 4f6dfce259244f05af4ea73ce304a4ff
run_link: ''
source: file:///C:/Users/NAVYA/Downloads/MY_PYTHON_PRACTICE/Innomatics_internship/jup_vir_env/Scripts/ML_flow_Sentiment_analysis/mlruns/972715570874921247/4f6dfce259244f05af4ea73ce304a4ff/artifacts/best_estimator
status: READY
status_message: null
storage_location: file:///C:/Users/NAVYA/Downloads/MY_PYTHON_PRACTICE/Innomatics_internship/jup_vir_env/Scripts/ML_flow_Sentiment_analysis/mlruns/972715570874921247/4f6dfce259244f05af4ea73ce304a4ff/artifacts/best_estimator
user_id: null
version: 3
